server:
  port: 8080
  servlet:
    session:
      timeout: 60m
      cookie:
        name: SESSION
        http-only: true
        secure: false # true для production с HTTPS
spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    url: ${DB_URL:jdbc:h2:file:./relayDB}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bl-service

